# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=32, verbose_name='部室')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=32, verbose_name='专业')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='投资项目名称')),
                ('p_id', models.CharField(max_length=32, unique=True, verbose_name='投资项目编码')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('money', models.BigIntegerField(verbose_name='投资项目金额')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.City')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_set', models.CharField(max_length=128, verbose_name='项目集')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='p_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.ProjectSet'),
        ),
        migrations.AddField(
            model_name='projects',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Profession'),
        ),
    ]
